<?php

namespace AppBundle\Repository;

/**
 * Baza_samolotowRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Baza_samolotowRepository extends \Doctrine\ORM\EntityRepository
{
}
