<?php

namespace AppBundle\Repository;

/**
 * Linie_lotniczeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Linie_lotniczeRepository extends \Doctrine\ORM\EntityRepository
{
}
