<?php

namespace AppBundle\Repository;

/**
 * Panel_lotniczyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Panel_lotniczyRepository extends \Doctrine\ORM\EntityRepository
{
}
