<?php

namespace AppBundle\Repository;

/**
 * PanstwaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PanstwaRepository extends \Doctrine\ORM\EntityRepository
{
}
